# Use a imagem base do Node.js
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie o package.json e o package-lock.json para o container
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código para o container
COPY . .

# Construa a aplicação React
RUN npm run build

# Use uma imagem base para servir arquivos estáticos
FROM nginx:alpine

# Copie a construção da aplicação React para o diretório do Nginx
COPY --from=0 /app/build /usr/share/nginx/html

# Exponha a porta que o Nginx está utilizando (geralmente 80)
EXPOSE 80

# Comando para rodar o Nginx
CMD ["nginx", "-g", "daemon off;"]
