###

// Get All

GET http://localhost:8080/tasks
content-type: application/json

###

// Post One

POST http://127.0.0.1:8081/new-task
content-type: application/json

{
  "title": "Task 4"
}

###

// Get One

GET http://localhost:8080/task/2
content-type: application/json

###

// Delete One

DELETE http://localhost:8080/delete/2
content-type: application/json

###