apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # base64 'postgres'
  SPRING_DATASOURCE_PASSWORD: ZGV2b3Bz      # base64  'devops'