# Use uma imagem base do Java
FROM openjdk:24-jdk

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo JAR do Spring Boot para o diretório de trabalho
COPY target/backend-0.0.1-SNAPSHOT.jar app.jar

# Exponha a porta que o Spring Boot está utilizando (geralmente 8080)
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]